export const DIGICELMARKETS = [
    'Anguilla',
    'Antigua & Barbuda',
    'Aruba',
    'Barbados',
    'Bermuda',
    'Bonaire',
    'British Virgin Islands',
    'Cayman',
    'Curacao',
    'Digicel Abroad',
    'Dominica',
    'El Salvador',
    'Fiji',
    'French Guiana',
    'Grenada',
    'Guadeloupe',
    'Guyana',
    'Haiti',
    'Jamaica',
    'Martinique',
    'Monserrat',
    'Nauru',
    'Panama',
    'Papua New Guinea',
    'Samoa',
    'St Kitts and Nevis',
    'St Lucia',
    'St Martin and St Barth',
    'St Vincent and The Grenadines',
    'Suriname',
    'Tonga',
    'Trinidad and Tobogao',
    'Turks and Caicos',
    'Vanuatu'
];
